GET http://localhost:8080/ping

###
POST http://localhost:8080/teams
Content-Type: application/json

{
    "name": "Devengers",
    "owner": "fake@example.com"
}

###
GET http://localhost:8080/teams/0ea115ac-6c6c-47b5-ae70-bd28b59895c84