name: "Run tests"

on:
  push:
    branches:
      - "feature/**"
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Unit tests
        run: make unit_tests
  integration_tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Integration tests
        run: make integration_tests
  component_tests:
    runs-on: ubuntu-latest
    name: Component tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Component tests
        run: make component_tests
